sudo: false
language: python

python:
  - 3.5

install:
  - pip install flake8
  # Sanity check
  - pip install -r requirements.txt

script:
  - flake8 launch.py

branches:
  only:
    - auto
    - master

notifications:
  email:
    on_success: never
  webhooks: http://homu.herokuapp.com/travis
